# This file was generated by GoReleaser. DO NOT EDIT.
cask "ttsbuddy" do
  version "0.13.2"

  on_macos do
    on_arm do
      sha256 "6f0e0c71657b6afd82492da6e0f888bcba1c12712c7d88b3105227a28459dc59"
      url "https://github.com/ngelik/ttsbuddy-cli/releases/download/v#{version}/ttsbuddy_#{version}_darwin_arm64.zip",
        verified: "github.com/ngelik/ttsbuddy-cli"
    end
    on_intel do
      sha256 "6b8cb01fe17247de96ea551f10ac66e64eb2b3a44332ef1c76d847c3f895aa6c"
      url "https://github.com/ngelik/ttsbuddy-cli/releases/download/v#{version}/ttsbuddy_#{version}_darwin_amd64.zip",
        verified: "github.com/ngelik/ttsbuddy-cli"
    end
  end
  on_linux do
    on_arm do
      sha256 "ef725662f82f4adcbbb56e3fe43fb252948e451922c49a3b940ced2c98392753"
      url "https://github.com/ngelik/ttsbuddy-cli/releases/download/v#{version}/ttsbuddy_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ngelik/ttsbuddy-cli"
    end
    on_intel do
      sha256 "b49dcf0ac32c92a6d365dc4017823e65c7a6333c1e0bfc18077be5fee038d161"
      url "https://github.com/ngelik/ttsbuddy-cli/releases/download/v#{version}/ttsbuddy_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ngelik/ttsbuddy-cli"
    end
  end

  name "ttsbuddy"
  desc "TTSBuddy CLI — convert text to speech from the command line"
  homepage "https://ttsbuddy.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ttsbuddy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ttsbuddy"]
    end
  end

  # No zap stanza required
end
