# This file was generated by GoReleaser. DO NOT EDIT.
cask "ttsbuddy" do
  version "0.9.1"

  on_macos do
    on_arm do
      sha256 "eb0753402a9ebf759ab9e07e737bf4885429c9911bb0f5420a02882d97003e81"
      url "https://github.com/ngelik/ttsbuddy-cli/releases/download/v#{version}/ttsbuddy_#{version}_darwin_arm64.zip",
        verified: "github.com/ngelik/ttsbuddy-cli"
    end
    on_intel do
      sha256 "038fdf9416c8fc17524af85dfd87151dc0d50053aeab6e7ed2f88c1ef6e27378"
      url "https://github.com/ngelik/ttsbuddy-cli/releases/download/v#{version}/ttsbuddy_#{version}_darwin_amd64.zip",
        verified: "github.com/ngelik/ttsbuddy-cli"
    end
  end
  on_linux do
    on_arm do
      sha256 "a892667876460f425d6cf874e6645a2fb367e2fe75890149fb151756a9da65d3"
      url "https://github.com/ngelik/ttsbuddy-cli/releases/download/v#{version}/ttsbuddy_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ngelik/ttsbuddy-cli"
    end
    on_intel do
      sha256 "c051aac4b72c4f8298a5cbee0286781ff2cd29c153c90997d986f529fc09099a"
      url "https://github.com/ngelik/ttsbuddy-cli/releases/download/v#{version}/ttsbuddy_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ngelik/ttsbuddy-cli"
    end
  end

  name "ttsbuddy"
  desc "TTSBuddy CLI — convert text to speech from the command line"
  homepage "https://ttsbuddy.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ttsbuddy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ttsbuddy"]
    end
  end

  # No zap stanza required
end
