# This file was generated by GoReleaser. DO NOT EDIT.
cask "ttsbuddy" do
  version "0.9.2"

  on_macos do
    on_arm do
      sha256 "ba50a21dbad494ca1ab3a4be606c93061e5c9a1a79a117077c4d06997feb57d5"
      url "https://github.com/ngelik/ttsbuddy-cli/releases/download/v#{version}/ttsbuddy_#{version}_darwin_arm64.zip",
        verified: "github.com/ngelik/ttsbuddy-cli"
    end
    on_intel do
      sha256 "298f4efb6320381eb801b4176392d359dd80af06932de2f586270323d83b8439"
      url "https://github.com/ngelik/ttsbuddy-cli/releases/download/v#{version}/ttsbuddy_#{version}_darwin_amd64.zip",
        verified: "github.com/ngelik/ttsbuddy-cli"
    end
  end
  on_linux do
    on_arm do
      sha256 "35f54a73ac30a360d6f748d78898df5f32a9db39e8bfc23e7471f2433fa10c29"
      url "https://github.com/ngelik/ttsbuddy-cli/releases/download/v#{version}/ttsbuddy_#{version}_linux_arm64.tar.gz",
        verified: "github.com/ngelik/ttsbuddy-cli"
    end
    on_intel do
      sha256 "a7d3859dda75145add1b5cc2a945da3e74cab4f82fdde9f4211c45d8bbd13222"
      url "https://github.com/ngelik/ttsbuddy-cli/releases/download/v#{version}/ttsbuddy_#{version}_linux_amd64.tar.gz",
        verified: "github.com/ngelik/ttsbuddy-cli"
    end
  end

  name "ttsbuddy"
  desc "TTSBuddy CLI — convert text to speech from the command line"
  homepage "https://ttsbuddy.com"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ttsbuddy"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/ttsbuddy"]
    end
  end

  # No zap stanza required
end
