# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ttsbuddy < Formula
  desc "TTSBuddy CLI — convert text to speech from the command line"
  homepage "https://ttsbuddy.com"
  version "0.6.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ngelik/ttsbuddy-cli/releases/download/v0.6.0/ttsbuddy_0.6.0_darwin_amd64.zip"
      sha256 "b4b777ad599d0358eaca69f78f8a201df3ca34c12b5d46a6e9bb5f516d9fc795"

      def install
        bin.install "ttsbuddy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ngelik/ttsbuddy-cli/releases/download/v0.6.0/ttsbuddy_0.6.0_darwin_arm64.zip"
      sha256 "782cf5b90dbfb94e1adb90cf300538d34ce05c581a5bae6984f5ca3c275cb395"

      def install
        bin.install "ttsbuddy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngelik/ttsbuddy-cli/releases/download/v0.6.0/ttsbuddy_0.6.0_linux_amd64.tar.gz"
        sha256 "2f5063b62fabb9395469949951242b2025975e8a37c42d5ffc5e7e4a65fd6e36"

        def install
          bin.install "ttsbuddy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngelik/ttsbuddy-cli/releases/download/v0.6.0/ttsbuddy_0.6.0_linux_arm64.tar.gz"
        sha256 "4ddc72fc0626b88c2b21d4af4eae21848b6f90f656a3d869cb704986e79a7da7"

        def install
          bin.install "ttsbuddy"
        end
      end
    end
  end
end
