# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ttsbuddy < Formula
  desc "TTSBuddy CLI — convert text to speech from the command line"
  homepage "https://ttsbuddy.com"
  version "0.3.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ngelik/ttsbuddy-cli/releases/download/v0.3.1/ttsbuddy_0.3.1_darwin_amd64.zip"
      sha256 "2353ed7ad1b91ed8187eab36c2b1d28a95b699b92d53607a318db41cf3843c10"

      def install
        bin.install "ttsbuddy"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ngelik/ttsbuddy-cli/releases/download/v0.3.1/ttsbuddy_0.3.1_darwin_arm64.zip"
      sha256 "834e0b79a5cb2d59f44a1eb76902855555bf14c456f3f4bd292289cba71faf0a"

      def install
        bin.install "ttsbuddy"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngelik/ttsbuddy-cli/releases/download/v0.3.1/ttsbuddy_0.3.1_linux_amd64.tar.gz"
        sha256 "8e6b45734bbc90e29e3047b6b855befb2fc8026e1568884957af34088fa5ee9e"

        def install
          bin.install "ttsbuddy"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/ngelik/ttsbuddy-cli/releases/download/v0.3.1/ttsbuddy_0.3.1_linux_arm64.tar.gz"
        sha256 "8bb0690e9d29ace3dcd09c586757e5e74e6a8e386dfa9a8b819a87978c4bba51"

        def install
          bin.install "ttsbuddy"
        end
      end
    end
  end
end
